### ISSUE TITLE
pubg_python.exceptions.NotFoundError: The specified resource was not found

### ISSUE THREAD

**Issue by Torxed** [ramonsaraiva/pubg-python#51]
```python
from pubg_python import PUBG, Shard

api_key = "..."
api = PUBG(api_key, Shard.PC_EU)

players = api.players().filter(player_names=['epickitten'])
player = players[0]
```

The following results in:

```
Traceback (most recent call last):
  File "pubg.py", line 7, in <module>
    player = players[0]
  File "/usr/lib/python3.7/site-packages/pubg_python-0.4.1-py3.7.egg/pubg_python/decorators.py", line 23, in wrapper
  File "/usr/lib/python3.7/site-packages/pubg_python-0.4.1-py3.7.egg/pubg_python/querysets.py", line 45, in fetch
  File "/usr/lib/python3.7/site-packages/pubg_python-0.4.1-py3.7.egg/pubg_python/clients.py", line 32, in request
pubg_python.exceptions.NotFoundError: The specified resource was not found
```

And I have no idea why. None of the player-filter searches works.
(`python setup.py install` from the latest branch. Python3.7 as the errors suggest)

**Comment by ramonsaraiva** [comment]
You probably requested that data when there was no information available for `epickitten`, maybe the player has not played recently when you requested it.
